# Generated by Django 4.2.16 on 2024-09-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_address_city_remove_address_state_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['membership'], name='store_custo_members_107be9_idx'),
        ),
    ]
